### ISSUE TITLE
[1.15.2] BioFuelGen Right click causes crash

### ISSUE THREAD

**Issue by ghost** [InnovativeOnlineIndustries/Titanium#53]
**Titanium Version: **
1.15.2-2.4.0
Forge 31.1.74

**Crashlog If Applicable (Upload to pastebin/gist): **
[https://pastebin.com/iq8deF8K](https://pastebin.com/iq8deF8K)

If you right click the Bio Fuel Generator block from IndustrialForegoing the game crashes. Just place the block then click it

Maybe same as Issue #52

**Comment by Vaelzan** [comment]
It's a similar issue to the one you linked to, but in a different part of the code. Same basic issue though - dividing by zero because the values aren't confirmed to be non-zero.

https://github.com/InnovativeOnlineIndustries/Titanium/blob/75e3847594fb481188217fd18f7852dce91967c0/src/main/java/com/hrznstudio/titanium/client/screen/addon/EnergyBarScreenAddon.java#L46

is the line that is causing the crash here.
